### ISSUE TITLE
in terminal vim, they all look the same

### ISSUE THREAD

**Issue by sunaku** [atelierbram/vim-colors_atelier-schemes#1]
I'm using terminal vim 7.4 inside xterm-256color.  After applying the first base16-atelier\* colorscheme, applying any other base16-atelier\* colorscheme seems to have no effect: they all appear the same. :scream:

**Comment by atelierbram** [comment]
@sunaku Thanks for the feedback. My colorschemes are made with support for true color in mind, so I suppose it doesn't support 256color out of the box, but to be honest [this topic](http://askubuntu.com/questions/67/how-do-i-enable-full-color-support-in-vim) confuses me. 
Are you on a Linux distro, like Ubuntu? If so I would like to suggest using the [Terminator](http://technicalworldforyou.blogspot.nl/2012/11/install-terminator-terminal-emulator-in.html) or maybe even better the [Guake](https://github.com/Guake/guake) app. Profile colors for these can be find in [the output folder in the original repo](https://github.com/atelierbram/syntax-highlighting/tree/master/atelier-schemes/output). I would guess that now, when you open Vim from these applications, Vim would pick up/inherit from those (_imported_) color-profiles, but I haven't tested those yet myself.

## Update

Just skimmed through one of your blogposts on colorschemes in the terminal, looks like you are really into this thing. Is it an idea to make a template for [Base16-Builder](https://github.com/chriskempson/base16-builder/), that relicates the pattern you posted in [your blogpost](http://sunaku.github.io/tomorrow-terminal-color-scheme.html) (_to be pasted into_ that so-called `~/.Xdefaults` file)?

**Comment by atelierbram** [comment]
@sunaku Sorry for the long wait and my initial confusion, but now these colorschemes, as well as the ones from [Base2Tone-vim](https://github.com/atelierbram/Base2Tone-vim) (DuoTones) _do support_ xterm-256color. After changing template engines I was able getting around to actually do this. You seem to be deep into this, and therefor I would appreciate it if you could test some of these themes and give feedback.
