### ISSUE TITLE
Theme variant (dark/light) does not correspond to name

### ISSUE THREAD

**Issue by plgruener** [atelierbram/vim-colors_atelier-schemes#4]
Regardless of the (file)name of the theme, one has to `set bg=light/dark` manually to switch between the dark and light variant. That makes having separate named Light/Dark files quite irrelevant.

Possible solutions:
1. remove duplicate files and suffixes
3. modify the templates so they switch background colors right in the color definitions (like in your Base2Tone templates).

edit: I'm using NeoVim v.0.4.3 in ArchLinux and in Terminal (but with `set termguicolors`)

**Comment by atelierbram** [comment]
Thanks for this, fixed with solution 2 ;)
